HEADERS = {
    'X-Access-Token': 'YOUR_TOKEN_HERE'
}
GROUP_NAME = 'YOUR_GROUP_NAME'
GROUP_ID = 'YOUR_GROUP_ID'

# path to private key json file
FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY = 'YOUR_KEY_FILE.json'
FIREBASE_DATABASE_URL = 'YOUR_DATABASE_URL'
