# GroupMe settings
GROUPME_URL = 'https://api.groupme.com/v3'
GROUPME_ACCESS_TOKEN = 'YOUR_TOKEN_HERE'
GROUP_NAME = 'YOUR_GROUP_NAME'
GROUP_ID = 'YOUR_GROUP_ID'

# Firebase settings
# path to private key json file
FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY = 'YOUR_KEY_FILE.json'
FIREBASE_DATABASE_URL = 'YOUR_DATABASE_URL'
